//! v0.3 codegen demo: take a [`FusedRecipe`] and emit equivalent Rust source.
//!
//! Pedagogical only. The emitted source is not compiled or loaded at runtime
//! — that would require cc/cargo integration and dynamic loading. The point
//! of this module is to show what a real codegen backend looks like: walk an
//! IR tree, produce target-language text, verify the text is well-formed.
//!
//! This mirrors how TorchInductor emits Triton (and how XLA emits HLO→LLVM):
//! the fused expression tree is the source-level form, and a backend walks
//! it to produce runnable code.

use super::fusion::{Expr, FusedRecipe};

/// Emit a self-contained Rust function that computes the recipe over
/// `n_inputs` input slices (all same length) and writes into `output`.
///
/// Signature of the emitted function:
/// ```ignore
/// fn kernel(inputs: &[&[f32]], output: &mut [f32]) { ... }
/// ```
pub fn emit_rust(recipe: &FusedRecipe, n_inputs: usize) -> String {
    let body = emit_expr(&recipe.expr);
    let mut out = String::new();
    out.push_str("// generated by toy-torch::graph::codegen::emit_rust\n");
    out.push_str(&format!(
        "// expects inputs.len() == {} and all inputs + output with matching length\n",
        n_inputs
    ));
    out.push_str("pub fn kernel(inputs: &[&[f32]], output: &mut [f32]) {\n");
    out.push_str(&format!("    assert_eq!(inputs.len(), {});\n", n_inputs));
    out.push_str("    let n = output.len();\n");
    for k in 0..n_inputs {
        out.push_str(&format!("    let in{k} = inputs[{k}];\n", k = k));
        out.push_str(&format!("    debug_assert_eq!(in{k}.len(), n);\n", k = k));
    }
    out.push_str("    for i in 0..n {\n");
    out.push_str(&format!("        output[i] = {body};\n"));
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

fn emit_expr(expr: &Expr) -> String {
    match expr {
        Expr::Input(k) => format!("in{}[i]", k),
        Expr::Const(t) => {
            if t.is_scalar() {
                format!("{}f32", t.data()[0])
            } else {
                // Materialized constants as inline arrays aren't supported in
                // this demo — scalar consts only.
                panic!("codegen: non-scalar Const not supported in emit_rust demo");
            }
        }
        Expr::Add(a, b) => format!("({} + {})", emit_expr(a), emit_expr(b)),
        Expr::Sub(a, b) => format!("({} - {})", emit_expr(a), emit_expr(b)),
        Expr::Mul(a, b) => format!("({} * {})", emit_expr(a), emit_expr(b)),
        Expr::Neg(a) => format!("(-{})", emit_expr(a)),
        Expr::Relu(a) => format!("({}.max(0.0))", emit_expr(a)),
    }
}
