//! JIT compilation of [`FusedRecipe`] kernels via emit_c + cc + dlopen.
//!
//! This is the v0.5 answer to v0.4's benchmark result: our fused-recipe
//! interpreter was 22× slower than a hand-rolled loop, and that gap was
//! "what codegen closes". Here we close it. We emit C for a fused recipe,
//! shell out to the system `cc` to build a shared library, dlopen the
//! library with `libloading`, and call the `kernel` symbol directly.
//!
//! Mirrors how TorchInductor emits Triton + loads `.cubin` — same pattern,
//! simpler target (CPU + C instead of GPU + PTX).
//!
//! ## Lifecycle
//! `JitKernel::compile(recipe, n_inputs)` → temp C source → `cc -O3 -shared -fPIC`
//! → `.dylib`/`.so`/`.dll` in `std::env::temp_dir()` → `libloading::Library::new`
//! → resolve `kernel` symbol → store function pointer + keep library alive.
//!
//! The compiled artifact is deleted via a best-effort cleanup; loss of the
//! file on shutdown is fine because it's in temp.
//!
//! ## Soundness sketch
//! The kernel function pointer is only valid while the `Library` it was
//! loaded from is alive. We store them in the same struct, with `fn_ptr`
//! declared *before* `lib` so Drop order is: fn_ptr (no-op, raw pointer) →
//! lib (unmaps the dylib). We never hand out the function pointer; calls go
//! through `JitKernel::call` which synthesizes the ABI at the call site.

use std::ffi::{CString, OsStr};
use std::path::PathBuf;
use std::process::Command;
use std::sync::atomic::{AtomicU64, Ordering};

use libloading::{Library, Symbol};

use super::fusion::{Expr, FusedRecipe};

/// Error cases for JIT compilation / loading.
#[derive(Debug)]
pub enum JitError {
    Io(std::io::Error),
    CcFailed { stderr: String, status: i32 },
    Load(libloading::Error),
    MissingSymbol(libloading::Error),
}

impl std::fmt::Display for JitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            JitError::Io(e) => write!(f, "io: {e}"),
            JitError::CcFailed { stderr, status } => {
                write!(f, "cc failed (exit {status}):\n{stderr}")
            }
            JitError::Load(e) => write!(f, "dlopen: {e}"),
            JitError::MissingSymbol(e) => write!(f, "missing `kernel` symbol: {e}"),
        }
    }
}

impl std::error::Error for JitError {}

impl From<std::io::Error> for JitError {
    fn from(e: std::io::Error) -> Self {
        JitError::Io(e)
    }
}

/// Emit portable C for a fused recipe. Signature:
/// ```c
/// void kernel(size_t n_inputs, const float **inputs, float *output, size_t n);
/// ```
pub fn emit_c(recipe: &FusedRecipe, n_inputs: usize) -> String {
    let body = emit_c_expr(&recipe.expr);
    let mut out = String::new();
    out.push_str("// generated by toy-torch::graph::jit::emit_c\n");
    out.push_str("#include <stddef.h>\n");
    out.push_str("static inline float relu(float x) { return x > 0.0f ? x : 0.0f; }\n\n");
    out.push_str("void kernel(size_t n_inputs, const float **inputs, float *output, size_t n) {\n");
    out.push_str(&format!("    if (n_inputs < {}) return;\n", n_inputs));
    for k in 0..n_inputs {
        out.push_str(&format!("    const float *in{k} = inputs[{k}];\n", k = k));
    }
    out.push_str("    for (size_t i = 0; i < n; ++i) {\n");
    out.push_str(&format!("        output[i] = {body};\n"));
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

fn emit_c_expr(expr: &Expr) -> String {
    match expr {
        Expr::Input(k) => format!("in{}[i]", k),
        Expr::Const(t) => {
            if t.is_scalar() {
                format!("{}f", t.data()[0])
            } else {
                panic!("emit_c: non-scalar Const not supported in v0.5");
            }
        }
        Expr::Add(a, b) => format!("({} + {})", emit_c_expr(a), emit_c_expr(b)),
        Expr::Sub(a, b) => format!("({} - {})", emit_c_expr(a), emit_c_expr(b)),
        Expr::Mul(a, b) => format!("({} * {})", emit_c_expr(a), emit_c_expr(b)),
        Expr::Neg(a) => format!("(-({}))", emit_c_expr(a)),
        Expr::Relu(a) => format!("relu({})", emit_c_expr(a)),
    }
}

static COUNTER: AtomicU64 = AtomicU64::new(0);

type KernelFn = unsafe extern "C" fn(usize, *const *const f32, *mut f32, usize);

/// A JIT-compiled fused kernel, backed by a dlopen'd shared library.
///
/// Drop order guarantees memory safety: `fn_ptr` is a raw pointer (no Drop
/// effect), `_lib` unmaps the dylib last. Since fields drop in declaration
/// order, placing `fn_ptr` before `_lib` ensures the library outlives the
/// function pointer.
pub struct JitKernel {
    fn_ptr: KernelFn,
    _lib: Library,
    _lib_path: PathBuf, // kept for debugging / cleanup
}

impl JitKernel {
    /// Compile a fused recipe to native code and load it.
    pub fn compile(recipe: &FusedRecipe, n_inputs: usize) -> Result<Self, JitError> {
        let c_src = emit_c(recipe, n_inputs);

        let uid = COUNTER.fetch_add(1, Ordering::Relaxed);
        let pid = std::process::id();
        let stem = format!("toy_torch_kernel_{}_{}", pid, uid);

        let tmp = std::env::temp_dir();
        let src_path = tmp.join(format!("{}.c", stem));
        let lib_name = format!(
            "{}{}.{}",
            std::env::consts::DLL_PREFIX,
            stem,
            std::env::consts::DLL_EXTENSION
        );
        let lib_path = tmp.join(&lib_name);

        std::fs::write(&src_path, c_src)?;

        // Invoke cc. Works for system `cc` on macOS/Linux; flags are portable.
        let output = Command::new("cc")
            .arg("-O3")
            .arg("-shared")
            .arg("-fPIC")
            .arg("-o")
            .arg(&lib_path)
            .arg(&src_path)
            .output()?;

        if !output.status.success() {
            return Err(JitError::CcFailed {
                stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
                status: output.status.code().unwrap_or(-1),
            });
        }

        // Load the dylib.
        let lib = unsafe { Library::new(&lib_path).map_err(JitError::Load)? };

        // Resolve the kernel symbol.
        let fn_ptr: KernelFn = unsafe {
            let sym: Symbol<KernelFn> = lib.get(b"kernel").map_err(JitError::MissingSymbol)?;
            *sym
        };

        // Best-effort cleanup of the C source; leave the .dylib alone while
        // it's dlopen'd.
        let _ = std::fs::remove_file(&src_path);

        Ok(JitKernel {
            fn_ptr,
            _lib: lib,
            _lib_path: lib_path,
        })
    }

    /// Call the compiled kernel. `inputs` must all have the same length as
    /// `output`. Panics otherwise.
    pub fn call(&self, inputs: &[&[f32]], output: &mut [f32]) {
        let n = output.len();
        for (i, s) in inputs.iter().enumerate() {
            assert_eq!(
                s.len(),
                n,
                "JitKernel::call: input {} length {} != output length {}",
                i,
                s.len(),
                n
            );
        }
        let ptrs: Vec<*const f32> = inputs.iter().map(|s| s.as_ptr()).collect();
        unsafe {
            (self.fn_ptr)(ptrs.len(), ptrs.as_ptr(), output.as_mut_ptr(), n);
        }
    }
}

impl Drop for JitKernel {
    fn drop(&mut self) {
        // Attempt to remove the dylib file. If this fails (common on Windows
        // while the handle is still open), it's OK — the OS will reclaim
        // temp/* on a reboot cleanup.
        let _ = std::fs::remove_file(&self._lib_path);
        // _ensures we reference the OsStr type; silence unused-path lint
        let _ = OsStr::new("");
        // The CString-using path isn't used here but we keep the import in
        // case emit_c ever emits a symbol name with a NUL that needs escaping.
        let _ = CString::new("kernel");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tensor::allclose;
    use crate::Tensor;

    #[test]
    fn emit_c_shape() {
        // relu((in0 - in1) * in0)
        let recipe = FusedRecipe::new(Expr::Relu(Box::new(Expr::Mul(
            Box::new(Expr::Sub(
                Box::new(Expr::Input(0)),
                Box::new(Expr::Input(1)),
            )),
            Box::new(Expr::Input(0)),
        ))));
        let src = emit_c(&recipe, 2);
        assert!(src.contains("const float *in0 = inputs[0];"));
        assert!(src.contains("const float *in1 = inputs[1];"));
        assert!(src.contains("relu(((in0[i] - in1[i]) * in0[i]))"));
    }

    #[test]
    fn jit_correctness() {
        // out = (x - y) * z — compiled kernel must match hand-computed.
        let recipe = FusedRecipe::new(Expr::Mul(
            Box::new(Expr::Sub(
                Box::new(Expr::Input(0)),
                Box::new(Expr::Input(1)),
            )),
            Box::new(Expr::Input(2)),
        ));
        let k = match JitKernel::compile(&recipe, 3) {
            Ok(k) => k,
            Err(e) => {
                eprintln!("skipping jit_correctness: {e}");
                return;
            }
        };
        let x = [1.0f32, 2.0, 3.0, 4.0];
        let y = [0.5f32, 0.5, 0.5, 0.5];
        let z = [2.0f32, 2.0, 2.0, 2.0];
        let mut out = vec![0.0f32; 4];
        k.call(&[&x, &y, &z], &mut out);
        let expected = Tensor::from_vec(&[1.0, 3.0, 5.0, 7.0], &[4]);
        assert!(
            allclose(&Tensor::from_vec(&out, &[4]), &expected, 1e-6),
            "jit output = {:?}",
            out
        );
    }
}
